#!/bin/bash -xe

test -d wifi_settings
python -m mypy example1.py example2.py test_test_3594_fix.py test_test_handler.py
rm -rf wifi_settings/__pycache__
rm -rf wifi_settings/.mypy_cache
mpremote cp -r wifi_settings wifi.cfg :/
mpremote cp *.py :/
mpremote run example1.py
